Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -3,17 +3,44 @@ name: Deploy Kaotika Battle Mobile
 on:
   push:
     branches:
-      - main
+      - main  
 
 jobs:
-  deploy:
-    runs-on: self-hosted
+  build:
+    runs-on: self-hosted  
+
     steps:
-      - name: Actualizar código
-        run: git pull origin main
-      - name: Instalar dependencias
-        run: npm install
-      - name: Construir React
-        run: npm run build
-      - name: Reiniciar apps en PM2
-        run: pm2 restart all
+    - name: Configuration
+      run: |
+        echo "Configuring Enviroment..."
+
+    - name: Verify cloned repo
+      run: |
+        if [ -d "$GITHUB_WORKSPACE/.git" ]; then
+          echo "Repository exists, updating..."
+          cd $GITHUB_WORKSPACE
+          git pull origin main
+        else
+          echo "Repository not found, cloning..."
+          git clone git@github.com:Oskar-Dam/kaotika-battle-mobile.git 
+        fi
+
+    - name: Installing dependencies
+      run: |
+        cd $GITHUB_WORKSPACE
+        npm install
+
+    - name: Build application
+      run: |
+        cd $GITHUB_WORKSPACE
+        npm run build
+
+    - name: Deploy application on pm2
+      run: |
+        pm2 stop kaotika-battle-mobile || true
+        pm2 restart kaotika-battle-mobile
+
+    - name: Clean after deploy
+      run: |
+        pm2 save
+        echo "Deploy complete"
